### PR TITLE
Changing the flipper service objects to match it’s new branding

### PR DESCRIPTION
**Pull request by Jey-T**
Changing the Flipper service attributes as our rebranded wallet (Shadow) is coming out soon.

### CODE REVIEW

**Comment by Jey-T** [comment]
@cybercent

**Comment by cybercent** [comment]
For info, we didn’t manage to use the repository to test the new icon.

**Comment by jribbink** [comment]
No problem, @cybercent .  I just tested it and it all looks good to me.  Here's a screenshot of how it looks for reference.

Screenshot 2023-11-28 at 11 40 53 AM

**Review by jribbink — APPROVED** [review]

**Comment by cybercent** [comment]
Thank you @jribbink LGTM

**Pull request merged**
