### PR TITLE
Reorder based on usage

### PR DESCRIPTION
**Pull request by chasefleming**

### CODE REVIEW

**Review by gregsantos — APPROVED** [review]

**Comment by cybercent** [comment]
Does the ordering in `services.json` count when displaying the wallet on the UI?

**Comment by srinjoyc** [comment]
Hi @cybercent, the ordering does matter for the **default UI**. However, if you use the [API version](https://developers.flow.com/tools/fcl-js/reference/discovery#api-version), you are free to order however you'd like - and this is the recommended option for most production apps - the default UI serves as a great way to quickly onboard and start developing initially. 

As far as usage goes, we hope to have more metrics in the future, but in order to serve the most number of users optimally today, we are tentatively ordering it via the current usage patterns we know of. There are two nuances to note here though:
- Dapper Wallet will **not** show up unless you explicitly opt-in through a configuration in FCL because it does not support the signing of any arbitrary transaction. 
- If a user has signed in via any wallet on Discovery in the past (on any website) then that wallet will be pulled up to the top of the list as 'last used' so this ordering will only be the default for net new users.

We hope to have better ways of exposing all wallets on the ecosystem soon and if you have any ideas here, would be happy to take it back to the team for consideration. This service is only as useful as the wallets on it so we really appreciate your feedback and definitely open to ideas.

**Comment by cybercent** [comment]
Hi @srinjoyc, thank you for your answer.

In conclusion the discovery widget only pushes Dapper Wallet as the main choice to new users on DApps that use the default discovery config. Looks like a great new user acquisition strategy to me. 

**If there is something to take back to the team is that there needs to be a clear separation between Flow and Dapper.**

I highly doubt that the priority for the Flow team was to spend engineering time on reordering a JSON when other PRs are waiting to be merged.

I'm interested to know if there is a public agenda, maybe similar to the one Ethereum has (https://github.com/ethereum/pm) where community member can participate in all the protocol and SDKs evolutions.

**Comment by srinjoyc** [comment]
@cybercent 

Just to clarify - Dapper needs additional configuration to be shown (not by default) but I do understand your concerns. You have brought up a good point and we'd like to make it easier to work with all wallet providers as well as provide more opportunities to guide the overall growth of the wallet ecosystem.

Closer to the end of the month, I'll be starting a working group for wallet providers on Flow where we can discuss FCL, Discovery, and more to get more visibility to the community over discussions and decisions being made. I'll reach out via email shortly with more details.

**Pull request merged**
