### PR TITLE
add previewnet entry into service

### PR DESCRIPTION
**Pull request by bthaile**
add previewnet entry into service

### CODE REVIEW

**Review by chasefleming — CHANGES_REQUESTED** [review]
You'll also need to change any mentions of `crescendo` to `previewnet` in the codebase.

**Comment by bthaile** [comment]
> You'll also need to change any mentions of `crescendo` to `previewnet` in the codebase.

I only found one instance of "crescendo" of which I updated in this PR. Is there other places I need to look outside of this repo?

**Comment by chasefleming** [comment]
Ok looks like it was already changed to previewnet everwhere else, except the services key wasn't so should be good: https://github.com/onflow/fcl-discovery/blob/master/helpers/constants.js#L8

Have you tested this?

**Comment by bthaile** [comment]
Yes, tested it locally using flow port.


image

**Review by chasefleming — APPROVED** [review]
Approved, but one more spot to check might be to make sure nothing needs to be different in the metadata for previewnet: https://github.com/onflow/fcl-discovery/blob/master/data/metadata.json

**Pull request merged**
