### PR TITLE
Add dapper SC endpoint

### PR DESCRIPTION
**Pull request by lmcmz**
Add dapper self custody ( dapper SC ) endpoint with `walletconnect` on `testnet` only.

### CODE REVIEW

**Comment by srinjoyc** [comment]
Context for opt-in only:
We will not be making this a generally available wallet but rather opt-in for the short term. This is because you currently still need to get gated access to the wallet via: https://docs.meetdapper.com/dapper-self-custody and is accessible through testflight for development purposes only. Dapper will consider GA in the future once out of beta.

**Comment by chasefleming** [comment]
Thanks @srinjoyc , @lmcmz can you add the `optIn` flag please?

**Comment by lmcmz** [comment]
Hey @srinjoyc , Thanks for calling it out. 
You are right, we can put the PR on hold, until we have out of beta release.
In the meantime, we can use default wallet connect modal as temporary solution.

**Comment by lmcmz** [comment]
BTW, I do see some improvements we can do with current fcl-discovery.
1.  If the dApp is missing the walletconnect configuration, we should show some alert text or filter it out the `WC/PRC` service. 
2. Replace wallet connect modal with new [web3Modal](https://github.com/WalletConnect/web3modal).

**Comment by chasefleming** [comment]
@lmcmz the `otpIn` flag actually doesn't show a wallet in Discovery unless it's explicity set, so should be good if that flag is added. A dapp would have to say show this wallet. Docs on it: https://www.meetdapper.com/dapper-self-custody

**Comment by lmcmz** [comment]
Close it

**Pull request closed without merging**
