### PR TITLE
Add NuFi wallet service and metadata

### PR DESCRIPTION
**Pull request by gyorgy-kurucz-vacuum**
Mainnet wallet is [available on the Chrome Web Store](https://chrome.google.com/webstore/detail/nufi/gpnihlnnodeiiaakbikldcihojploeca).
Testnet build is [available here](https://assets.nu.fi/extension/testnet/nufi-cwe-testnet-latest.zip).

### CODE REVIEW

**Comment by chasefleming** [comment]
@gyorgy-kurucz-vacuum Exciting! Let me try this out. Which services does NuFi support?

**Comment by chasefleming** [comment]
@gyorgy-kurucz-vacuum Loving the UI on this wallet. Question for you: with extensions it's harder to have a testnet and mainnet service because you're typically only shipping one to the chrome store. Any way we could use the deployed chrome extension as the testnet service and inside of the app there is a way to switch between testnet and mainnet? That's what other extensions are doing. If you need to download a zip file on testnet it may be a little odd for people developing with Discovery. Although if you have a link to download the zip file we could also use that maybe as the install_link for testnet.

**Comment by gyorgy-kurucz-vacuum** [comment]
Thanks for your quick response!

> Loving the UI on this wallet.

Nice to hear that :)

> Which services does NuFi support?

Right now we only support the minimum requirements for `authn` and `authz`. (This may be expanded in the future of course if our flow connector gets any traction.)

> Any way we could use the deployed chrome extension as the testnet service and inside of the app there is a way to switch between testnet and mainnet?

Unfortunately that's a limitation we have right now, we don't support dynamic switching between networks.

We don't officially support testnet in any capacity, the testnet build only exists for development purposes. (Not sure if/when this will change. Also tagging @refi93 as he probably has a better picture of this.)

So if adding the testnet entry to `services.json` implies any kind of official support, we would rather not have it there. (I only added it because the README specifically asked for a testnet demo version.)

If absolutely necessary I guess the zip download could be added, but we would rather not have anyone rely on that for now...

What would be the best solution for you?

**Comment by refi93** [comment]
> We don't officially support testnet in any capacity, the testnet build only exists for development purposes. (Not sure if/when this will change. Also tagging @refi93 as he probably has a better picture of this.)

I confirm that - our officially released extension has only mainnet support, the extension with testnet support is just for development purposes and not officially distributed

**Comment by refi93** [comment]
The development build of the testnet extension can be downloaded from here: https://assets.nu.fi/extension/testnet/nufi-cwe-testnet-latest.zip

**Comment by chasefleming** [comment]
Ok lets just remove it from testnet and leave the mainnet service. Can you also add `"optIn": true` to the service. We are marking anything that doesn't support authn, authz, and user signing as opt-in. We can remove it when user signing is added. In the meantime, putting your mainnet address on the table for opt-in wallets in the readme will give people visibility of that as an option.

**Comment by gyorgy-kurucz-vacuum** [comment]
I see. Well the visibility would be quite important for us, so in this case we will put this PR on hold and prioritize implementing the user signing service. (Should be done in 1-2 weeks if everything goes well.)

Thanks for the feedback. I will close this PR, and we will open another one once a new version with user signing support has been released.

**Pull request closed without merging**
