### PR TITLE
Add NuFi wallet service and metadata

### PR DESCRIPTION
**Pull request by refi93**
Follow up on https://github.com/onflow/fcl-discovery/pull/108 as the NuFi extension v2.3.3 with user signing support has just been released

Mainnet wallet is [available on the Chrome Web Store](https://chrome.google.com/webstore/detail/nufi/gpnihlnnodeiiaakbikldcihojploeca).
Testnet build is [available here](https://assets.nu.fi/extension/testnet/nufi-cwe-testnet-latest.zip).

cc @chasefleming

### CODE REVIEW

**Comment by chasefleming** [comment]
Awesome, thanks! We'll test out the wallet. Thanks for adding user signing!

**Comment by chasefleming** [comment]
Tested out the wallet and it's great! Ready to merge, but a merge conflict that need fixing. Mind fixing that?

One thing I noticed is that entering your password is required on every authorization. Assuming that's desired behavior, right?

**Comment by gregsantos** [comment]
Testnet build working smoothly for transaction and user-signing (with verification)!
Also seeing password prompt on each.
A great new addition to Wallet Discovery!

**Comment by refi93** [comment]
> Tested out the wallet and it's great! Ready to merge, but a merge conflict that need fixing. Mind fixing that?

Done :+1: 
 
> One thing I noticed is that entering your password is required on every authorization. Assuming that's desired behavior, right?

The "connection" confirmation prompt on each authorization (with the connect/reject option) is expected, entering the password should be needed only for the first one for the given browser session, unless the "remember login" option in the password prompt was unchecked or if the user chooses to switch to a different profile - are you sure it was asking for the password on each authorization (unexpected, unless "remember login" was unchecked) and it wasn't just the connection prompt (expected)?

**Review by chasefleming — APPROVED** [review]
Looks great. Excited about another wallet for the ecosystem!

**Pull request merged**
